//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroHWTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int HeroID { get; set; }
        public int Gender { get; set; }
        public int Level { get; set; }
        public string ImageFilePath { get; set; }
    }
}
