//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroHWTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monster
    {
        public int MonsterID { get; set; }
        public string imageFilePathAlive { get; set; }
        public string imageFilePathDead { get; set; }
        public int isAlive { get; set; }
    }
}
