//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroHWTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserInfoID { get; set; }
        public string Username { get; set; }
        public int Hero_Gender { get; set; }
        public int Level { get; set; }
        public int currExp { get; set; }
    }
}
